//~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import { ShellStep } from 'aws-cdk-lib/pipelines'
import { AwsCredentials, GitHubWorkflow } from 'cdk-pipelines-github'
import { Construct } from 'constructs'

export class CdkPipeline extends GitHubWorkflow {
  public constructor(scope: Construct) {
    super(scope, 'Pipeline', {
      awsCreds: AwsCredentials.fromOpenIdConnect({
        gitHubActionRoleArn: 'arn:aws:iam::934979133063:role/CommonCicd-RootGitHubGithubActionsACC56793-79JE121HOPUG',
      }),
      preBuildSteps: [
        {
          name: 'Setup Node.js',
          uses: 'actions/setup-node@v3',
          with: { 'node-version': '16.13.0' },
        },
        {
          name: 'Configure AWS Credentials',
          uses: 'aws-actions/configure-aws-credentials@v1',
          with: {
            'aws-region': 'us-east-2',
            'role-to-assume': 'arn:aws:iam::934979133063:role/CommonCicd-RootGitHubGithubActionsACC56793-79JE121HOPUG',
          },
        },
        {
          name: 'AWS CodeArtifact Login',
          run: 'npm run ca:login',
        },
      ],
      synth: new ShellStep('Build', {
        commands: ['npm ci', 'npm run build'],
      }),
      workflowName: 'deploy',
      workflowPath: '.github/workflows/deploy-cdk.yml',
      workflowTriggers: {
        push: {
          branches: ['main'],
        },
        workflowDispatch: {},
      },
    })
  }
}
